added BookRepository and BookService
holsoni/book-store pull request #1
Opened 2023-08-31 18:01 UTC by holsoni

2023-08-31 23:28 UTC, Someboty reviewed
Great work! I'll leave my suggestions, but they're not critical.

2023-08-31 23:28 UTC, Someboty commented on pom.xml
> +        </dependency>
Separate dependencies with empty line for better readability

2023-09-01 07:38 UTC, nacenik requested changes
Good, let's improve it a little bit :)

2023-09-01 07:38 UTC, nacenik commented on pom.xml
> +            <version>3.1.3</version>
Do you really need to put starter version if it is the same as parent version?

2023-09-01 07:38 UTC, nacenik commented on pom.xml
> +
extra empty line

2023-09-01 07:38 UTC, nacenik commented on src/main/java/com/example/bookstore/BookStoreApplication.java
> +    }
you can rewrite it using lambda

2023-09-01 07:38 UTC, nacenik commented on src/main/java/com/example/bookstore/model/Book.java
> +    private BigDecimal price;
could price be null? 
<img width="353" alt="image" src="https://github.com/holsoni/book-store/assets/32339836/cbd86573-c77b-46b7-bdc7-f271fe9f980e">

2023-09-01 07:38 UTC, nacenik commented on .github/workflows/ci.yml
you can delete this block of code and your ci should work 
```
      - uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event.pull_request && success() }}
        with:
          github-token: ${{ github.token }}
      - uses: mate-academy/auto-reject-action@v2
```

2023-09-04 14:18 UTC, vovasalyha approved these changes
GJ!

2023-09-04 14:18 UTC, vovasalyha commented on src/main/java/com/example/bookstore/BookStoreApplication.java
```suggestion
```

2023-09-04 18:19 UTC, merged