Implementation of ShoppingCart
holsoni/book-store pull request #10
Opened 2023-09-15 08:23 UTC by holsoni

2023-09-19 12:57 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/dto/shoppingcart/CartItemDto.java
> +public class CartItemDto {
is it possible to add some validations to DTOs or if for example, the quantity will be -10 it is ok?

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(currentUser.getId())
Triple code duplication (addToCart, getShoppingCart, create)

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/12-create-shopping_car_cart_item-table.yaml
add empty line please

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/12-create-shopping_car_cart_item-table.yaml
> +    author: holsoni
It is difficult to identify author of change set, please set your name and surname in author section

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/user/impl/UserServiceImpl.java
> +
```suggestion
```

2023-09-19 12:57 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/shoppingcart/impl/ShoppingCartServiceImpl.java
> +        cartItem.setBook(book);
Is it possible to move mapping logic to mappers?

2023-09-20 16:26 UTC, vovasalyha approved these changes

2023-09-20 16:26 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/shoppingcart/AddCartItemRequestDto.java
> +    private Long bookId;
can bookId be null?

2023-09-21 11:20 UTC, merged