Implemented Order
holsoni/book-store pull request #11
Opened 2023-09-18 11:49 UTC by holsoni

2023-09-19 12:40 UTC, CodeWebWeaver requested changes
You can add additional handlers for exceptions if you want.
Also I can`t find how you clear your shopping cart after placing order

2023-09-19 12:40 UTC, CodeWebWeaver commented on src/main/java/com/example/bookstore/controller/OrderController.java
> +        orderService.updateOrderStatus(id, requestDto, authentication);
You shoudn`t use authentication here
You need PreAuthorize User

2023-09-19 12:40 UTC, CodeWebWeaver commented on src/main/java/com/example/bookstore/controller/OrderController.java
> +        return orderService.getByIdAndOrderId(orderId, itemId);
You need to authorize user here

2023-09-19 12:40 UTC, CodeWebWeaver commented on src/main/java/com/example/bookstore/controller/OrderController.java
> +
You need authorize user here

2023-09-19 12:40 UTC, CodeWebWeaver commented on src/main/java/com/example/bookstore/service/order/impl/OrderServiceImpl.java
> +    private final OrderRepository orderRepository;
reduncant field

2023-09-19 12:40 UTC, CodeWebWeaver commented on src/main/java/com/example/bookstore/service/order/impl/OrderServiceImpl.java
> +    }
you can split it in method

2023-09-22 12:44 UTC, andrii-hoienko requested changes
Nice, but some improvements required

2023-09-22 12:44 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/order/impl/OrderServiceImpl.java
> +                                  Authentication authentication) {
Do you use authentication here?

2023-09-22 12:44 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/order/impl/OrderServiceImpl.java
> +    private Order getOrder(PlaceOrderRequestDto requestDto,
```suggestion
    private Order createOrder(PlaceOrderRequestDto requestDto,
```

2023-09-22 12:44 UTC, andrii-hoienko commented on src/main/java/com/example/bookstore/service/order/impl/OrderServiceImpl.java
> +    private OrderItem mapCartItemToOrderItem(CartItem cartItem, Order order) {
Is it possible to use mapper for mapping?

2023-09-22 12:44 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/13-create-orders-table.yaml
> +                  defaultValue: false
add empty line

2023-09-25 12:18 UTC, andrii-hoienko approved these changes
Good job!

2023-09-25 14:15 UTC, merged