Testing
holsoni/book-store pull request #14
Opened 2023-09-25 14:45 UTC by holsoni

2023-09-27 01:34 UTC, Someboty requested changes
GJ! Left few suggestions.

2023-09-27 01:34 UTC, Someboty commented on src/test/java/com/example/bookstore/controller/BookControllerTest.java
> +    private static final CreateBookRequestDto INVALID_CREATE_BOOK_REQUEST_DTO =
Bad naming

2023-09-27 01:34 UTC, Someboty commented on src/test/resources/database/scripts/delete-all-from-book_category.sql
> +DELETE FROM book_category;
Forgot empty line

2023-09-27 01:34 UTC, Someboty commented on src/test/resources/database/scripts/delete-all-from-books.sql
> +DELETE FROM book;
And here

2023-09-27 01:34 UTC, Someboty commented on src/test/resources/database/scripts/delete-all-from-category.sql
> +DELETE FROM category;
And here

2023-09-27 01:34 UTC, Someboty commented on src/test/resources/database/scripts/insert-book-category-relations-for-harry_potter.sql
> +VALUES (1, 1);
And here

2023-09-29 14:03 UTC, vovasalyha approved these changes
GJ

2023-10-08 08:05 UTC, merged