Added usage of JPARepository and added logic for search() method usin…
holsoni/book-store pull request #3
Opened 2023-09-05 15:46 UTC by holsoni

…g CriteriaQuery

2023-09-05 16:14 UTC, keda-vlad requested changes
Nice, but only one thing)

2023-09-05 16:14 UTC, keda-vlad commented on src/main/java/com/example/bookstore/controller/BookController.java
>  @RestController
Book Endpoints:
GET: /api/books (Retrieve book catalog) (should be done in the previous PR)
GET: /api/books/{id} (Retrieve book details) (should be done in the previous PR)
POST: /api/books (Create a new book) (should be done in the previous PR)
PUT: /api/books/{id} (Update a specific book)  <------------------------------------ u miss this

2023-09-05 20:21 UTC, keda-vlad approved these changes
Nice)

Optional, maybe better to create constant for "author" in AuthorSpecificationProvider  and in BookSpecificationBuilder

2023-09-05 20:23 UTC, keda-vlad commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +        Optional<Book> fromDb = bookRepository.findById(id);
Do u need it?

2023-09-06 15:29 UTC, vovasalyha approved these changes
GJ

2023-09-06 15:29 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/impl/BookServiceImpl.java
> +    public BookDto update(Long id, UpdateBookRequestDto updateBookRequestDto) {
Fetching an entity before update is usually safer.

2023-09-06 16:49 UTC, merged